/*!
 * Copyright 2016 Werdenfels-Gymnasium All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
!function(){var app=angular.module("wgHilfe",["ngMaterial","ngRoute","hc.marked"]);app.config(function($mdThemingProvider){$mdThemingProvider.theme("default").primaryPalette("blue").accentPalette("grey")}),app.run(function($rootScope,$mdSidenav){$rootScope.toggleSidenav=function(){$mdSidenav("left").toggle()},$rootScope.$on("$routeChangeStart",function(){$rootScope.loadingRoute=!0}),$rootScope.$on("$routeChangeSuccess",function(){$rootScope.loadingRoute=!1}),$rootScope.isLoading=function(){return $rootScope.loadingRoute&&$rootScope.loadingGuide}}),app.config(function($routeProvider,$locationProvider){$routeProvider.when("/",{templateUrl:"partials/home.tmpl.html"}).when("/guide/:id",{templateUrl:"partials/guide.tmpl.html",controller:"GuideController"}).otherwise({templateUrl:"partials/404.tmpl.html"}),$locationProvider.html5Mode(!1)})}();
function GuideController($scope,$routeParams,$location,GuideService){function loadGuide(){if(angular.isDefined(mergedGuides[id])){var guide=mergedGuides[id];$scope.title=guide.title,$scope.path="content/guides/"+guide.path}else $scope.title="Fehler",$scope.error="Die gesuchte Anleitung konnte nicht in unserer Datenbank gefunden werden."}var mergedGuides=[],id=$routeParams.id;GuideService.fetchData().then(function(data){for(var key in data){var item=data[key];if(item.collapse)for(var ckey in item.items)mergedGuides[ckey]=item.items[ckey];else mergedGuides[key]=item}loadGuide()},function(error){$scope.title="Fehler",$scope.error="Es ist ein Fehler beim Laden der Anleitungen aufgetreten."})}angular.module("wgHilfe").controller("GuideController",GuideController);
function RootController($rootScope,$scope,$routeParams,GuideService){$rootScope.loadingGuide=!0,GuideService.fetchData().then(function(data){$rootScope.loadingGuide=!1,$scope.guides=data},function(error){new Error("There occoured an error while reading the guides: "+error)}).finally(function(){$scope.loadingGuide=!0})}angular.module("wgHilfe").controller("RootController",RootController);
function MdCollapseMenuItem($compile,$mdUtil){function postLink(scope,element){function updateIsOpen(){ulElement.style.height=isActive?_collapseHeight+"px":0}var _collapseHeight,isActive=!1,ulElement=element[0].querySelector("ul"),collapsePlaceholder=angular.element('<md-menu-item type="icon">{{ ngLabel }}</md-menu-item>');collapsePlaceholder=$compile(collapsePlaceholder)(scope),requestAnimationFrame(function waitForElement(){_collapseHeight=ulElement.getBoundingClientRect().height,_collapseHeight?updateIsOpen():requestAnimationFrame(waitForElement)}),element.prepend(collapsePlaceholder),collapsePlaceholder.on("click",function(){_collapseHeight&&(isActive=!isActive,updateIsOpen())})}return{restrict:"E",scope:{ngLabel:"@"},transclude:!0,template:"<ul><div ng-transclude></div></ul>",link:postLink}}angular.module("wgHilfe").directive("mdCollapseMenuItem",MdCollapseMenuItem);
angular.module("wgHilfe").directive("mdMenuItem",function(){return{restrict:"AE",transclude:!0,template:function(elem,attr){return"icon"===attr.type?'<md-button layout="row" ng-href="{{ link }}"><span ng-transclude flex></span><md-icon md-svg-src="img/collapse-menu.svg"></md-icon></md-button>':'<md-button ng-href="{{ link }}"><span ng-transclude></span></md-button>'},link:function(scope,element,attr){scope.link=attr.ngHref||""}}});
function GuideService($q,$http){this.fetchData=function(){return $q(function(resolve){$http.get("content/guides/guides.json",{headers:{"Content-type":"application/json"}}).then(function(success){resolve(success.data)},function(failure){resolve(failure)})})}}angular.module("wgHilfe").service("GuideService",GuideService);