sudo: true
language: node_js
node_js:
  - '4.2.3'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - chmod a+x ./scripts/deploy.sh
  - git config --global user.email "gschwepa@werdenfels-gymnasium.de"
  - git config --global user.name "DevVersion's Commit Donator"
  - npm install bower -g
  - bower install
script:
  - 'gulp build'
after_success:
  - './scripts/deploy.sh'