sudo: false
language: node_js
node_js:
  - '4.2.3'
branches:
  only:
    - master
before_script:
  - chmod a+x ./scripts/deploy.sh
  - git config --global user.email "gschwepa@werdenfels-gymnasium.de"
  - git config --global user.name "DevVersion's Commit Bot"

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./scripts/deploy.sh'