sudo: false

language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - git config --global user.email "gschwepa@werdenfels-gymnasium.de"
  - git config --global user.name "Werdenfels-Gymnasium"

script:
  - gulp build

after_success:
  - './scripts/deploy.sh'
